site_name: pg-schemata
theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: index.md
  - API Reference: pg-schemata.md
  - Where Modifiers: where-modifiers.md
  - Schema Types: schemaTypes.md