/*
 * Copyright © 2026 – present NapSoft LLC. All rights reserved.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { z } from 'zod';
import pgPromise from 'pg-promise';
import TableModel from '../../src/TableModel.js';
import SchemaDefinitionError from '../../src/SchemaDefinitionError.js';
import { columnSetCache } from '../../src/utils/schemaBuilder.js';
import type { DbConnection, TableSchema } from '../../src/schemaTypes.js';

// No vi.mock here on purpose: these tests assert the *shape* of `error.cause`,
// which is only meaningful when the validators are the real ones generated by
// generateZodFromTableSchema. Mocking schemaBuilder would stub them away and
// the assertions would pass against nothing.
const pgp = pgPromise({});
const stubDb = {
  one: async () => ({}),
  any: async () => [],
  oneOrNone: async () => null,
  result: async () => ({ rowCount: 0 }),
  none: async () => null,
} as unknown as DbConnection;

function makeSchema(table: string): TableSchema {
  return {
    dbSchema: 'public',
    table,
    columns: [
      { name: 'id', type: 'uuid', notNull: true, default: 'gen_random_uuid()' },
      { name: 'email', type: 'varchar(255)', notNull: true },
      { name: 'age', type: 'integer' },
    ],
    constraints: { primaryKey: ['id'] },
  };
}

function makeModel(table: string): TableModel {
  return new TableModel(stubDb, pgp, makeSchema(table));
}

/**
 * The contract every catch site shares: `.cause` is the Zod issue array, not
 * the ZodError itself and not undefined. `err.errors` was removed in zod 4, so
 * an unmigrated site silently sets `.cause` to undefined — `Array.isArray`
 * alone catches that, and the issue-shape assertions pin the rest.
 */
function expectZodIssueCause(error: unknown, expectedPath: string): void {
  expect(error).toBeInstanceOf(SchemaDefinitionError);
  const cause = (error as SchemaDefinitionError).cause;
  expect(Array.isArray(cause)).toBe(true);

  const issues = cause as { path: PropertyKey[]; code: string }[];
  expect(issues.length).toBeGreaterThan(0);
  expect(issues.some(i => i.path.includes(expectedPath))).toBe(true);
  expect(typeof issues[0]!.code).toBe('string');
}

describe('SchemaDefinitionError.cause carries Zod issues', () => {
  beforeEach(() => {
    columnSetCache.clear();
  });

  it('validateDto sets cause to the issue array (QueryModel)', () => {
    const model = makeModel('cause_validate_dto');
    let caught: unknown;

    try {
      model.validateDto(
        { email: 123 },
        model._schema.validators!.insertValidator,
        'Insert DTO'
      );
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeDefined();
    expectZodIssueCause(caught, 'email');
  });

  it('validateDto reports the offending index for an array payload', async () => {
    const model = makeModel('cause_validate_dto_array');
    let caught: unknown;

    try {
      model.validateDto(
        [{ email: 'ok@example.com' }, { email: 123 }],
        model._schema.validators!.insertValidator,
        'Bulk Insert DTO'
      );
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeDefined();
    const issues = (caught as SchemaDefinitionError).cause as {
      path: PropertyKey[];
    }[];
    expect(Array.isArray(issues)).toBe(true);
    expect(issues[0]!.path).toEqual([1, 'email']);
  });

  it('insert rejects with cause set to the issue array (TableModel)', async () => {
    const model = makeModel('cause_insert');

    const caught = await model
      .insert({ email: 123 } as never)
      .then(() => null)
      .catch((err: unknown) => err);

    expectZodIssueCause(caught, 'email');
  });

  it('update rejects with cause set to the issue array (TableModel)', async () => {
    const model = makeModel('cause_update');

    const caught = await model
      .update('11111111-1111-4111-8111-111111111111', { age: 'old' } as never)
      .then(() => null)
      .catch((err: unknown) => err);

    expectZodIssueCause(caught, 'age');
  });

  it('updateWhere rejects with cause set to the issue array (TableModel)', async () => {
    const model = makeModel('cause_update_where');

    const caught = await model
      .updateWhere({ email: 'someone@example.com' }, { age: 'old' } as never)
      .then(() => null)
      .catch((err: unknown) => err);

    expectZodIssueCause(caught, 'age');
  });

  it('leaves cause as the raw error when the failure is not a ZodError', () => {
    const model = makeModel('cause_non_zod');
    const boom = new Error('not a zod failure');
    let caught: unknown;

    try {
      model.validateDto({}, {
        parse: () => {
          throw boom;
        },
      } as never);
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(SchemaDefinitionError);
    expect((caught as SchemaDefinitionError).cause).toBe(boom);
  });
});

describe('upsert and bulkUpsert validate their input', () => {
  // Both went straight from sanitizeDto to SQL, so invalid types, the email
  // check, and colProps.validator rules all reached the database despite the
  // docs stating every write is validated. Both are async, so they reject
  // rather than throw.
  beforeEach(() => {
    columnSetCache.clear();
  });

  it('upsert rejects a wrong-typed value with an issue array', async () => {
    const model = makeModel('cause_upsert');

    const caught = await model
      .upsert({ email: 123 } as never, ['id'])
      .then(() => null)
      .catch((err: unknown) => err);

    expectZodIssueCause(caught, 'email');
  });

  it('bulkUpsert reports the offending record index', async () => {
    const model = makeModel('cause_bulk_upsert');

    const caught = await model
      .bulkUpsert([{ email: 'ok@example.com' }, { email: 123 }] as never, [
        'id',
      ])
      .then(() => null)
      .catch((err: unknown) => err);

    expect(caught).toBeInstanceOf(SchemaDefinitionError);
    const issues = (caught as SchemaDefinitionError).cause as {
      path: PropertyKey[];
    }[];
    expect(Array.isArray(issues)).toBe(true);
    expect(issues[0]!.path).toEqual([1, 'email']);
  });

  it('upsert enforces a colProps.validator', async () => {
    const schema = makeSchema('cause_upsert_custom');
    schema.columns = schema.columns.map(col =>
      col.name === 'age'
        ? { ...col, colProps: { validator: z.number().int().min(21) } }
        : col
    );
    const model = new TableModel(stubDb, pgp, schema);

    const caught = await model
      .upsert({ email: 'a@b.com', age: 18 } as never, ['id'])
      .then(() => null)
      .catch((err: unknown) => err);

    expectZodIssueCause(caught, 'age');
  });
});

describe('colProps.validator survives schema cloning', () => {
  // The constructor deep-clones the caller's schema. cloneDeep walked the Zod
  // internals and produced an object that looked like a validator but had no
  // _zod.def.checks, so composing it into the generated z.object threw a
  // TypeError on the first parse — breaking every custom validator, which is
  // the documented escape hatch for interval, bytea, and unmapped types.
  beforeEach(() => {
    columnSetCache.clear();
  });

  const intervalSchema = (
    table: string,
    validator: z.ZodType
  ): TableSchema => ({
    dbSchema: 'public',
    table,
    columns: [
      {
        name: 'id',
        type: 'uuid',
        notNull: true,
        default: 'gen_random_uuid()',
      },
      { name: 'duration', type: 'interval', colProps: { validator } },
    ],
    constraints: { primaryKey: ['id'] },
  });

  it('validates rather than throwing a TypeError', async () => {
    const model = new TableModel(
      stubDb,
      pgp,
      intervalSchema('clone_ok', z.string())
    );

    await expect(
      model.insert({ duration: '1 day' } as never)
    ).resolves.toBeDefined();

    const caught = await model
      .insert({ duration: 123 } as never)
      .then(() => null)
      .catch((err: unknown) => err);

    // A real validation failure, not a crashed validator.
    expectZodIssueCause(caught, 'duration');
  });

  it('keeps the caller validator instance by reference', () => {
    const validator = z.string();
    const model = new TableModel(
      stubDb,
      pgp,
      intervalSchema('clone_ref', validator)
    );

    const column = model._schema.columns.find(c => c.name === 'duration');
    expect(column?.colProps?.validator).toBe(validator);
  });

  it('still does not mutate the schema the caller passed', () => {
    const schema = intervalSchema('clone_no_mutate', z.string());
    schema.hasAuditFields = true;
    const before = schema.columns.length;

    const model = new TableModel(stubDb, pgp, schema);

    expect(schema.columns.length).toBe(before);
    expect(schema.columns.some(c => c.name === 'created_at')).toBe(false);
    expect(model.schema.columns.some(c => c.name === 'created_at')).toBe(true);
  });
});
